### ISSUE TITLE
Tutorial: Identifying a transiting planet signal in Kepler or TESS light curves

### ISSUE THREAD

**Issue by nksaunders** [barentsen/notebooks#19]
This notebook introduces the Lightkurve `BoxLeastSquaresPeriodogram` and walks users through the basics of a fundamental reason for using Kepler or TESS data—finding transiting planets. 

While many users will be familiar with the BLS method, I think it's useful to have a quick refresher with some figures that clearly show the approach taken by BLS.

Then, the notebook will provide simple steps to use the `BoxLeastSquaresPeriodogram` object to identify a transiting exoplanet signal in both Kepler and TESS. It will show users how to extract a transit model and transit mask, which can be used to remove the identified signal and search the remainder of the light curve for additional transiting planets.

(optional, but I think it would be cool →) Finally, it will show a concise gif of how the interactive BLS periodogram works, with references to the lightkurve docs for more information. This gif could be reused for an "Interactively analyzing Kepler/K2 and TESS data with Lightkurve" notebook, which I think would be fun to write!

By the end of this tutorial, you will:
 - Understand the "Box-Least Squares" (BLS) method for identifying transit signals
 - Know how to use the Lightkurve `BoxLeastSquaresPeriodogram` to identify a transiting planet
 - Estimate the period, epoch, and duration of the transit
 - Plot the phase-folded transit light curve
 - Be familiar with the interactive Box Least Squares periodogram in Lightkurve

**Comment by barentsen** [comment]
:+1:

**Comment by nksaunders** [comment]
@barentsen This tutorial is ready for review.

**Comment by nksaunders** [comment]
Note: title changed to **"Identifying transiting planet signals in a Kepler light curve"** to better reflect the content of the tutorial

**Comment by barentsen** [comment]
Hmmm both `colab` and my local install seem stuck on the line that says `lc_collection.stitch().flatten(901)`.  Did you experience any problems with that?

**Comment by nksaunders** [comment]
@barentsen It was working fine for me yesterday. This appears to be an issue introduced by lightkurve [#844](https://github.com/KeplerGO/lightkurve/pull/844), which is causing lightkurve to download simultaneous short and long cadence Kepler data. I added `cadence='long'` to the search function and it's now behaving as expected again.

**Comment by barentsen** [comment]
@nksaunders Ah! That makes sense. Thank you!

This is an intentional change by #844, because TESS has many targets for which only short and no long-cadence products exist.

**Comment by barentsen** [comment]
Thanks @nksaunders!  This is a really excellent tutorial.  I love it!

Nitpicking: in two or three places I turned unnamed arguments into named keyword argument, e.g. it is good practice to use
```
lc.fold(period=planet_b_period, epoch_time=planet_b_t0) 
```
instead of
```
lc.fold(planet_b_period, planet_b_t0) 
```
because it makes the code more resilient against any future API changes.

Otherwise this is a really fun, informative, and important tutorial.  It is ready for copy editing! :+1:

**Comment by barentsen** [comment]
The filename is `Identifying a transiting planet signal in Kepler or TESS light curves.ipynb`.

**Comment by lglattly** [comment]
@nksaunders and @barentsen I finished copy editing this tutorial. I loved reading this one -- finding transiting exoplanets is so fascinating!! 

I made minor copy edits throughout, and I also named "planet b" earlier in section 3, as I was little confused when it was named in section 4 and had to go back and look at the code more carefully. Hopefully that change is alright! Otherwise, this one is all set on my end and ready to go!

**Comment by barentsen** [comment]
Awesome :+1:

**Comment by nksaunders** [comment]
Perfect, thanks @lglattly!!

**Comment by barentsen** [comment]
This notebook has successfully been merged into `spacetelescope/notebooks`.  Thanks everyone!  Closing the issue...
