### ISSUE TITLE
Tutorial: Using Full Frame Image Products with Lightkurve

### ISSUE THREAD

**Issue by ojhall94** [barentsen/notebooks#5]
This notebook will form part of the series: Getting started with _Kepler_ and _K2_ data products.

In this third notebook, we will focus on downloading and studying a Full Frame Image. This will include i.e. looking at the flux in individual pixels, setting a rudimentary aperture, cutting out TPFs,  and plotting the background. The user should already be familiar with light curve objects (#3) and target pixel files (#4). When talking about aperture photometry, it should point forward to #2.

We can draw inspiration from existing Lightkurve tutorials:
- [How to cut out Target Pixel Files from Kepler Superstamps or TESS FFIs](http://docs.lightkurve.org/tutorials/03-cutting-out-tpfs-from-tess-ffis.html)

---

Learning Goals:
- How to access FFI data
- What does the metadata mean?
- What does a FFI look like, and how can I understand the content of different pixels?
- What are different features on the FFI and how can I understand them (dead columns, lens flare, etc)
- How do I plot the flux content of pixels?
- How do I set an aperture mask?
- How do I cut out a TPF?

To think about:
- Do we include Kepler superstamp functionality here?
- Do we focus the tutorial on the superstamps and include TESS FFIs as secondary (as this should be Kepler focused)

**Comment by ojhall94** [comment]
Hey all,

I'm a little lost on where to start with this one. I think might be easier to have two separate notebooks, so we have:

- How to cut a target pixel file out of a TESS FFI, and
- How to use Kepler and K2 Superstamp Files

As far as I can tell there are no FFIs for Kepler or K2, but I could be mistaken.

**Comment by barentsen** [comment]
Thanks for posting your thinking @ojhall94!

Here are my thoughts: 
* I would cover superstamps (= Target Pixel Files convering a large area) and FFI's in separate notebooks, because they are different beasts.  Of course both notebooks could explain the difference and link to each other.
* Kepler took multiple FFIs each Quarter, and K2 took about two each Campaign.  You can find a full list of the Kepler FFIs in Table 3 of the [Data Characteristics Handbook](https://archive.stsci.edu/kepler/manuals/Data_Characteristics.pdf).  Of course the total number of FFIs is very small (a few dozen) compared to TESS.
* The `spacetelescope/notebooks` repo currently has two notebooks on FFIs:
  * https://github.com/spacetelescope/notebooks/blob/master/notebooks/MAST/Kepler/Kepler_FFI/kepler_ffi.ipynb
  * https://github.com/spacetelescope/notebooks/blob/master/notebooks/MAST/K2/K2_FFI/beginner_how_to_use_ffi.ipynb
...one option could be to to simply review and edit these if we feel there is anything about them that can be improved.
* If cutting a TPF out of Kepler FFI's works well in Lightkurve, that could certainly merit a notebook.  I don't remember if Lightkurve's cut out tool works on Kepler data?

**Comment by ojhall94** [comment]
Thats enough to get me started, thanks! I'll play around with the info & tools and feed back about what I think the next step should be.

**Comment by barentsen** [comment]
It looks like we won't complete this notebook before the end of the project, so I'm closing this issue.  It was worth trying! :+1:
